'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowLeft, Loader2, Sparkles } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useCreateCampaign, useAIGenerateBrief } from '@/lib/queries';
import { toast } from '@/hooks/use-toast';

const campaignSchema = z.object({
  title: z.string().min(5, 'Title must be at least 5 characters').max(100, 'Title must be at most 100 characters'),
  description: z.string().min(10, 'Description must be at least 10 characters').max(500, 'Description must be at most 500 characters'),
  brief: z.string().optional(),
  requirements: z.string().optional(),
  budgetMin: z.number().min(0, 'Budget cannot be negative'),
  budgetMax: z.number().min(0, 'Budget cannot be negative'),
  platforms: z.array(z.string()).min(1, 'Please select at least one platform'),
  targetNiches: z.array(z.string()).min(1, 'Please select at least one niche'),
  targetLocations: z.array(z.string()).optional(),
  targetAgeRange: z.string().optional(),
  targetGender: z.string().optional(),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  applicationDeadline: z.string().optional(),
  isPublished: z.boolean().default(false),
});

type CampaignFormData = z.infer<typeof campaignSchema>;

const niches = [
  'Beauty', 'Skincare', 'Fashion', 'OOTD', 'Food', 'Travel', 'Fitness', 'Tech',
  'Gaming', 'Parenting', 'Home', 'Digital', 'Cars', 'Pets', 'Music', 'Photography'
];

const platforms = [
  { value: 'instagram', label: 'Instagram' },
  { value: 'tiktok', label: 'TikTok' },
  { value: 'youtube', label: 'YouTube' },
  { value: 'twitter', label: 'Twitter/X' },
  { value: 'pinterest', label: 'Pinterest' },
  { value: 'snapchat', label: 'Snapchat' },
  { value: 'twitch', label: 'Twitch' },
];

const locations = [
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego',
  'Dallas', 'San Jose', 'Austin', 'Miami', 'London', 'Paris', 'Berlin', 'Tokyo', 'Sydney', 'Toronto'
];

export default function CreateCampaignPage() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [aiBrief, setAiBrief] = useState('');
  
  const createCampaign = useCreateCampaign();
  const generateBrief = useAIGenerateBrief('temp');

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors },
  } = useForm<CampaignFormData>({
    resolver: zodResolver(campaignSchema),
    defaultValues: {
      platforms: [],
      targetNiches: [],
      targetLocations: [],
      budgetMin: 0,
      budgetMax: 0,
      isPublished: false,
    },
  });

  const selectedPlatforms = watch('platforms');
  const selectedNiches = watch('targetNiches');
  const selectedLocations = watch('targetLocations');

  const handleGenerateBrief = async () => {
    const title = watch('title');
    const description = watch('description');
    const requirements = watch('requirements');
    
    if (!title || !description) {
      toast({
        title: 'Tip',
        description: 'Please fill in the title and description first',
        variant: 'destructive',
      });
      return;
    }

    try {
      toast({
        title: 'Generating with AI',
        description: 'Generating professional brief, please wait...',
      });
      // Simulate AI generation for now
      await new Promise(resolve => setTimeout(resolve, 2000));
      const brief = `# Campaign Brief

## Campaign Overview
Thank you for your interest! Please read this brief carefully to ensure high-quality content creation.

## Influencer Requirements
- Stable content output on ${selectedPlatforms.join(', ')}
- Good content creation skills and aesthetics
- Ability to deliver on time

## Content Requirements
- Content must be original, no plagiarism
- Must genuinely experience the product or service
- Positive content, complying with platform rules

## Delivery Standards
- Deliver content according to agreed quantity and format
- Submit on time, no delays
- Communicate in time if there are issues

## Notes
- Maintain good communication during collaboration
- Comply with all reasonable requirements from the brand
- Do not delete or modify published content without permission

## Evaluation Metrics
- Content engagement rate
- Content quality
- On-time delivery rate

---
*This brief is generated by AI, brands can adjust as needed*`;
      setAiBrief(brief);
      setValue('brief', brief);
      toast({
        title: 'Success',
        description: 'AI has generated a professional brief for you',
      });
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Generation failed, please try again',
        variant: 'destructive',
      });
    }
  };

  const onSubmit = async (data: CampaignFormData) => {
    try {
      await createCampaign.mutateAsync({
        data: {
          title: data.title,
          description: data.description,
          brief: data.brief,
          requirements: data.requirements,
          budget_min: data.budgetMin * 100, // Convert to cents
          budget_max: data.budgetMax * 100, // Convert to cents
          platforms: data.platforms,
          target_niches: data.targetNiches,
          target_locations: data.targetLocations,
          target_age_range: data.targetAgeRange,
          target_gender: data.targetGender,
          start_date: data.startDate,
          end_date: data.endDate,
          application_deadline: data.applicationDeadline,
          is_public: data.isPublished,
          status: data.isPublished ? 'OPEN' : 'DRAFT',
        },
      });

      toast({ title: 'Success', description: 'Campaign created successfully!' });
      router.push('/dashboard/campaigns');
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error?.message || 'Creation failed, please try again',
        variant: 'destructive',
      });
    }
  };

  const nextStep = () => setStep(step + 1);
  const prevStep = () => setStep(step - 1);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/dashboard/campaigns">
          <Button variant="ghost" size="icon">
            <ArrowLeft className="w-5 h-5" />
          </Button>
        </Link>
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Create Campaign</h1>
          <p className="text-gray-500 mt-1">Publish a new marketing campaign</p>
        </div>
      </div>

      {/* Progress */}
      <div className="flex items-center justify-center gap-2">
        {[1, 2, 3].map((s) => (
          <div key={s} className="flex items-center">
            <div className={`w-10 h-10 rounded-full flex items-center justify-center font-medium ${
              step >= s ? 'bg-purple-600 text-white' : 'bg-gray-200 text-gray-500'
            }`}>
              {s}
            </div>
            {s < 3 && (
              <div className={`w-16 h-1 mx-2 ${step > s ? 'bg-purple-600' : 'bg-gray-200'}`} />
            )}
          </div>
        ))}
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Step 1: Basic Info */}
        {step === 1 && (
          <Card>
            <CardHeader>
              <CardTitle>Basic Info</CardTitle>
              <CardDescription>Fill in basic campaign information</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="title">Campaign Title *</Label>
                <Input
                  id="title"
                  {...register('title')}
                  placeholder="e.g. Looking for beauty influencers for new product promotion"
                />
                {errors.title && (
                  <p className="text-sm text-red-500">{errors.title.message}</p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="description">Campaign Description *</Label>
                <Textarea
                  id="description"
                  {...register('description')}
                  placeholder="Briefly introduce your campaign and collaboration needs..."
                  rows={4}
                />
                {errors.description && (
                  <p className="text-sm text-red-500">{errors.description.message}</p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="requirements">Specific Requirements</Label>
                <Textarea
                  id="requirements"
                  {...register('requirements')}
                  placeholder="Detail your requirements and expectations..."
                  rows={4}
                />
              </div>

              <div className="flex justify-end">
                <Button type="button" onClick={nextStep}>
                  Next
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Step 2: Requirements */}
        {step === 2 && (
          <Card>
            <CardHeader>
              <CardTitle>Requirements</CardTitle>
              <CardDescription>Set campaign requirements and conditions</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Platforms */}
              <div className="space-y-2">
                <Label>Target Platforms *</Label>
                <div className="flex flex-wrap gap-2 mt-2">
                  {platforms.map((platform) => (
                    <button
                      key={platform.value}
                      type="button"
                      onClick={() => {
                        const current = selectedPlatforms;
                        if (current.includes(platform.value)) {
                          setValue('platforms', current.filter((p) => p !== platform.value));
                        } else {
                          setValue('platforms', [...current, platform.value]);
                        }
                      }}
                      className={`px-4 py-2 rounded-lg border transition-colors ${
                        selectedPlatforms.includes(platform.value)
                          ? 'border-purple-600 bg-purple-50 text-purple-600'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                    >
                      {platform.label}
                    </button>
                  ))}
                </div>
                {errors.platforms && (
                  <p className="text-sm text-red-500">{errors.platforms.message}</p>
                )}
              </div>

              {/* Niches */}
              <div className="space-y-2">
                <Label>Target Niches *</Label>
                <div className="flex flex-wrap gap-2 mt-2">
                  {niches.map((niche) => (
                    <button
                      key={niche}
                      type="button"
                      onClick={() => {
                        const current = selectedNiches;
                        if (current.includes(niche)) {
                          setValue('targetNiches', current.filter((n) => n !== niche));
                        } else {
                          setValue('targetNiches', [...current, niche]);
                        }
                      }}
                      className={`px-3 py-1.5 rounded-full text-sm transition-colors ${
                        selectedNiches.includes(niche)
                          ? 'bg-purple-600 text-white'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {niche}
                    </button>
                  ))}
                </div>
                {errors.targetNiches && (
                  <p className="text-sm text-red-500">{errors.targetNiches.message}</p>
                )}
              </div>

              {/* Budget */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="budgetMin">Min Budget (USD) *</Label>
                  <Input
                    id="budgetMin"
                    type="number"
                    {...register('budgetMin', { valueAsNumber: true })}
                    placeholder="500"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="budgetMax">Max Budget (USD) *</Label>
                  <Input
                    id="budgetMax"
                    type="number"
                    {...register('budgetMax', { valueAsNumber: true })}
                    placeholder="2000"
                  />
                </div>
              </div>

              {/* AI Brief Generator */}
              <div className="border rounded-lg p-4 bg-gray-50">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-purple-600" />
                    <Label>AI Brief Generator</Label>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleGenerateBrief}
                    disabled={generateBrief.isPending}
                  >
                    {generateBrief.isPending ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      'Generate'
                    )}
                  </Button>
                </div>
                {aiBrief && (
                  <Textarea
                    {...register('brief')}
                    placeholder="AI generated brief will appear here..."
                    rows={6}
                  />
                )}
              </div>

              <div className="flex justify-between">
                <Button type="button" variant="outline" onClick={prevStep}>
                  Previous
                </Button>
                <Button type="button" onClick={nextStep}>
                  Next
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Step 3: Details */}
        {step === 3 && (
          <Card>
            <CardHeader>
              <CardTitle>Details</CardTitle>
              <CardDescription>Set other campaign details</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Locations */}
              <div className="space-y-2">
                <Label>Target Locations</Label>
                <div className="flex flex-wrap gap-2 mt-2">
                  {locations.map((location) => (
                    <button
                      key={location}
                      type="button"
                      onClick={() => {
                        const current = selectedLocations || [];
                        if (current.includes(location)) {
                          setValue('targetLocations', current.filter((l) => l !== location));
                        } else {
                          setValue('targetLocations', [...current, location]);
                        }
                      }}
                      className={`px-3 py-1.5 rounded-full text-sm transition-colors ${
                        selectedLocations?.includes(location)
                          ? 'bg-purple-600 text-white'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      {location}
                    </button>
                  ))}
                </div>
              </div>

              {/* Dates */}
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="startDate">Start Date</Label>
                  <Input
                    id="startDate"
                    type="date"
                    {...register('startDate')}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="endDate">End Date</Label>
                  <Input
                    id="endDate"
                    type="date"
                    {...register('endDate')}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="applicationDeadline">Application Deadline</Label>
                  <Input
                    id="applicationDeadline"
                    type="date"
                    {...register('applicationDeadline')}
                  />
                </div>
              </div>

              {/* Publish */}
              <div className="flex items-center gap-3 p-4 border rounded-lg">
                <input
                  type="checkbox"
                  id="isPublished"
                  {...register('isPublished')}
                  className="w-4 h-4 rounded"
                />
                <div className="flex-1">
                  <Label htmlFor="isPublished" className="cursor-pointer">
                    Publish Immediately
                  </Label>
                  <p className="text-sm text-gray-500">
                    If checked, the campaign will be visible to influencers immediately after creation
                  </p>
                </div>
              </div>

              <div className="flex justify-between">
                <Button type="button" variant="outline" onClick={prevStep}>
                  Previous
                </Button>
                <Button type="submit" disabled={createCampaign.isPending}>
                  {createCampaign.isPending ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Creating...
                    </>
                  ) : (
                    'Create Campaign'
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </form>
    </div>
  );
}
